### ISSUE TITLE
How to reset Captcha

### ISSUE THREAD

**Issue by frostymarvelous** [appleboy/react-recaptcha#14]
How is reset handled?

**Comment by appleboy** [comment]
@frostymarvelous I will implement it as soon as possible.

**Comment by danbahrami** [comment]
@appleboy I was thinking of creating a pull request for this feature, I propose exposing a reset method which could be accessed via a callback ref. So usage would look like...

```
resetCaptcha() {
    this.recaptcha.reset();
}

render() {
    <Recaptcha
        ref={e => this.recaptcha = e}
        {...otherProps}
    />
}
```

Let me know your thoughts and I can implement and document.

**Comment by frostymarvelous** [comment]
Refs. Hmm.

Anyway,, I think it is a good idea.

**Comment by appleboy** [comment]
@danbahrami Good. I will take it.

**Comment by danbahrami** [comment]
@frostymarvelous I would say refs is the most declarative way of doing this but I'm open to suggestions. do you have a different api in mind?

**Comment by frostymarvelous** [comment]
I was speaking from something I remembered from the docs concerning deprecation.
However, I went back and checked and it was only referring to "string" refs.

So yeah, it is a great way of doing it.

**Comment by appleboy** [comment]
@frostymarvelous Please try the `2.2.3` version and see [the example](https://github.com/appleboy/react-recaptcha/blob/master/example/main.js).

**Comment by frostymarvelous** [comment]
A big thanks to @danbahrami for the work put in.
And thanks to @appleboy for the project in the first place.
