### ISSUE TITLE
v.2.2.0 bundle includes react source code

### ISSUE THREAD

**Issue by elboman** [appleboy/react-recaptcha#178]
Hi,
I think 2.2.0 bundle includes React source and maybe something else. I updated the library and my application isn't working anymore.

I compared the bundles:
```
2.1.1: 3Kb
2.2.0: 176Kb
```
I tried to look for something in past commits but I can't seem to find anything. I guess something went wrong before publishing to npm.

**Comment by danbahrami** [comment]
yeah, I'm seeing the same thing, looks like it's published a dev build.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Hi @danbahrami @elboman 

Please update to `2.2.3` version.
