### ISSUE TITLE
ReCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by daywong1119** [appleboy/react-recaptcha#181]
I got the error when inflating the view by code below:
```
     <div className="form-group" id="captcha-holder">
        <Recaptcha sitekey="xxx" render="explicit" verifyCallback={this.onCaptchaVerify}/>
    </div>
```

    recaptcha__en.js:286 Uncaught Error: ReCAPTCHA placeholder element must be an element or id

**Comment by MrHash** [comment]
Several people have this problem it seems. Any advice?

**Comment by marudhupandiyang** [comment]
Try adding `onloadCallback` to `Recaptcha`. Something similar to below

    <div className="form-group" id="captcha-holder">
        <Recaptcha sitekey="xxx" render="explicit" verifyCallback={this.onCaptchaVerify} onloadCallback={this.onloadCallback}/>
    </div>

**Comment by wil93** [comment]
I solved it by adding `render="explicit"` and `onloadCallback={console.log.bind(this, "recaptcha loaded")}`

I don't know why those two things (especially the onload thing) are required, but this check may be the cause of them being required: https://github.com/appleboy/react-recaptcha/blob/53768e246d5af97f8a7293a6c457a69153bfd2cd/src/index.js#L105

**Comment by Daniel1971** [comment]
Thanks a lot, wil93.

**Comment by chris-allnutt** [comment]
#186  doesn't fix this issue.   The issue doesn't present itself on hard reloads, only soft reloads when the data is already cached. forcing a dev to add render and onloadcallback even when the method is empty makes little sense.

**Comment by JZebra** [comment]
I'm also having this issue in v2.3.11, but only in certain parts of my app.
