### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated.

### ISSUE THREAD

**Issue by laduke** [appleboy/react-recaptcha#189]
> Use the prop-types package from npm instead.

Pretty sure I'm getting this deprecation warning from this package. 

`import React, { PropTypes, Component } from 'react';`

PR welcome?

**Comment by appleboy** [comment]
PR welcome. Thanks.

**Comment by laduke** [comment]
Sorry. Can't figure it out. I changed to 
`import PropTypes from 'prop-types';`
and somehow PropTypes is is undefined when I run the test

https://www.npmjs.com/package/prop-types

**Comment by halkeye** [comment]
Did you remove the old PropTypes?

Probably best to create the PR with the work in progress and ask for feedback.

**Comment by shawnrice** [comment]
See PR #194.

**Comment by laduke** [comment]
Looks like it's merged. Thanks #194 !
