### ISSUE TITLE
Reset method isn't working

### ISSUE THREAD

**Issue by mdsantosdev** [appleboy/react-recaptcha#217]
I tried to use the reset method with the only captcha that I had in my page and It's showing me this error: 

> Invalid ReCAPTCHA client id: 0

**Comment by Stoneski93** [comment]
I ma having the same error.

**Comment by ivanandrianto** [comment]
Same problem here. I use Recaptcha V2

Have you found any workarounds? This bug is very annoying

**Comment by oxynad** [comment]
Can anyone fix this issue please?

**Comment by sarneeh** [comment]
Hey guys! I've encountered the same issue using `react-recaptcha` and decided to create my own library. It has some improvements comparing to this lib and most important - it works completely fine! 🚀 

Library: https://github.com/sarneeh/reaptcha
Example: https://sarneeh.github.io/reaptcha/

Hope it helps! 😄 🎉
