### ISSUE TITLE
Available props

### ISSUE THREAD

**Issue by Zyets** [appleboy/react-recaptcha#218]
Please include all available props to your documentation. I broke my brain trying to set proper lang to recaptacha. Official google documentation says to add hl param to script path, but that does not work, thanks to your line number 103 at index.js! I agree! It is correct way to set params like that, but how in world i would know that from your readme... gosh...

i m really sorry for yelling... i've had a deadline today, hopefully it will pass successfully...

Anyway, thanks for your plugin!
best wishes)

**Comment by appleboy** [comment]
You can see the prop list first.  https://github.com/appleboy/react-recaptcha/blob/master/src/index.js#L4-L38

**Comment by Zyets** [comment]
Yeah! I did exactly what you say, but after a whole hour spent on googling whats wrong with google recaptcha...
I mean, i was probably wrong, when i forgot to look in source code first. But, man, it's impolite to send everybody to sources. You either include full description to your examples or do not write anything at all - let people puzzle everything out themselves. You did not even use that prop here: 
https://github.com/appleboy/react-recaptcha/blob/master/example/main.js

I'm not judging you anyway. You've wrote a nice plugin! I'm grateful for that and even will give a star. That issue is just a recommendation.

**Comment by appleboy** [comment]
Yes, it is ok. maybe someone like you or me can send PR to update the document.

**Comment by andyfry01** [comment]
@appleboy I'd be glad to do a PR on this to update the documentation, are you still taking PRs for this?

**Comment by appleboy** [comment]
@andyfry01 PR welcome. Thanks.

**Comment by Zyets** [comment]
Reading my old issues... gosh.. sorry for being douchebag! I was young and inexperienced.
