### ISSUE TITLE
Limited test coverage

### ISSUE THREAD

**Issue by andyfry01** [appleboy/react-recaptcha#221]
Hi again!

The test cases in [the test spec](https://github.com/appleboy/react-recaptcha/blob/master/__tests__/recaptcha-test.js) aren't very robust, basically consisting of a single 'it should exist' test. 

I'd be glad to do a PR with some more test cases to improve coverage for the component.

🏗

**Comment by appleboy** [comment]
@andyfry01 Thanks. PR welcome.

**Comment by andyfry01** [comment]
Closed by PR #233
