### ISSUE TITLE
setInterval in constructor causes memory leak on server

### ISSUE THREAD

**Issue by joxerTMD** [appleboy/react-recaptcha#247]
Hello there!
setInterval [in constructor](https://github.com/appleboy/react-recaptcha/blob/0eb373916dcca78d137d20eedca46d6961cac5ee/src/index.js#L50) causes memory leak on server because componentWillUnmount() and therefore clearInterval() is not being called during server rendering.
I've prepared #246 to fix this. It would be cool if you merge it as soon as possible :)

**Comment by appleboy** [comment]
merged. Done.

**Comment by appleboy** [comment]
bump to `2.3.10`
