### ISSUE TITLE
The auto-detect of the language doesn't work.

### ISSUE THREAD

**Issue by sergiop** [appleboy/react-recaptcha#258]
As reported in [reCaptcha v2 docs](https://developers.google.com/recaptcha/docs/display#js_param), to allow reCaptcha to auto-detect the language, you don't have to specify `hl` param.

<img width="519" alt="Schermata 2019-06-07 alle 16 32 18" src="https://user-images.githubusercontent.com/2235134/59111702-d9b66680-8941-11e9-8bd5-ba5158946cf6.png">

If you set it to `en` in the `defaultProps`, it's impossible to set it to undefined and there isn't a way to enable the auto-detection of the language.

I created a PR to fix this: https://github.com/appleboy/react-recaptcha/pull/257

Let me know what do you think and if you can merge it. Thanks for your attention. 🙂

**Comment by appleboy** [comment]
Closed via #257
