### ISSUE TITLE
Navigating with react-router, it doesn't seem to work without refresh.

### ISSUE THREAD

**Issue by jhunexjun** [appleboy/react-recaptcha#27]
I use this recaptcha for my reactjs project. As I navigate from home page going to the registration, the captcha doesn't show without refresh.

**Comment by kjanoudi** [comment]
@jhunexjun  Try doing a hard "reset" on it, by calling grecaptcha.reset(). just a thought

**Comment by danielkhan** [comment]
This is the same problem as described in https://github.com/appleboy/react-recaptcha/issues/190.
A hard reset doesn't do the trick.

**Comment by jhunexjun** [comment]
I already solved this one guys long time ago but I guess what I did was I added callback function just like this.
```
<Recaptcha sitekey={sitekey} render="explicit" onloadCallback={reCaptchaCallback} />
```

Actually the callback doesn't have anything inside. Check below:
```
var reCaptchaCallback = function() {};
```
