### ISSUE TITLE
Disabling in a automated test environment

### ISSUE THREAD

**Issue by CGottschallJ** [appleboy/react-recaptcha#323]
Hey,

I am looking to disable/work through react-recaptcha in a cypress automated test environment. 

I've seen in the documentation [here](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do) that a secondary `siteKey` and `secretKey` can be passed into the recaptcha however I am not seeing that is possible in the documentation for react-recaptcha. Is anyone aware of a way to successfully bypass the pop up in cypress or is there anything in the package that would allow for this?

Thanks!

EDIT: I figured out that passing the key from the link above works!

**Comment by Wajihah-Kainat** [comment]
Hey @CGottschallJ can you please share your code, I want to know how it worked. I ran into the same thing. Help from your end would be appreciated
